### ISSUE TITLE
Idea for making history sandbox

### ISSUE THREAD

**Issue by SNWSeth** [Yulin-W/making-history-sandbox#35]
**I accidentally posted an idea to the old version, it was meant to be sent here. Anyways, here is the idea:**

_'I still use the old version of the alternate history timeline maker. I use it because you can play the timeline automatically and even on different speeds. It's just an idea, but could this be added to the new version too?'_

**Comment by Yulin-W** [comment]
Just added play time line feature, should be live now (you might need to do a full refresh though for your browser to reload the new version). 
Closing this issue.
