### ISSUE TITLE
An enhancement idea for the timeline thing

### ISSUE THREAD

**Issue by SNWSeth** [Yulin-W/making-history-sandbox#37]
Woah, this was updated very quickly! I love the timeline thing. I don't know if this will lag it more: but can you make it so you can put the speed to something similar like the 4x in the alternate history timeline editor. It makes it look smooth and like a timelapse.

I often make scenarios with this that are around 2-3 years (each day a new event, being like 900 events), If they can move smoother like in a timelapse way that would be very cool. Maybe more possibilities like:
1x 2x 4x 8x 16x (already implemented) but also some things like 32x, 64x and 128x.

Also I've got one more question, is **Issues** a good place to submit suggestions?

**Comment by SNWSeth** [comment]
Also just another idea, cause I'm checking how it is to make a scenario on the new editor, it's a bit harder, because the circles are a bit small, and after having 20 events it's hard to create a new one, you have to scroll and you have to do that manually every time (if you create large scenario with many events.)

Maybe you can add a thing to the side just like the alternate history timeline editor, and it being able to be minimized again.

In case you don't know what I mean, here's a screenshot:
![image](https://user-images.githubusercontent.com/100678600/191303505-bd9775d3-0565-47a1-91b5-1df55104a676.png)

**Comment by Yulin-W** [comment]
Thanks for the idea! The tabular timeline feature should be up and running now. You can click/adding/deleting events there (but editing will still need to be done in the event box on the bottom left).

Regarding playspeed, the app has got some lag issues that I won't be able to fix anytime soon; so sorry about that. I guess a makeshift (albeit regrettably inconvenient) way would be to record a gif/screen capture and then play that faster.

And yes, suggestions is issues are fine. Albeit, I should mention that that I'm not actively updating the app anymore. I just happen to be on holiday this week and so have the time to make changes. With that said, feel free to post issues/suggestions, but I can't make any guarantees about timely updates in the future.

Closing the issue now.
